name: Deploy dev

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & push images
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: tomaciazekecho.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push echo app
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:app"
          tags: tomaciazekecho.azurecr.io/echo:${{ github.sha }}
          push: true

  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inflate chart values
        run: |
          ./bake.sh
        env:
          DOCKER_REGISTRY: tomaciazekecho.azurecr.io
          IMAGE_VERSION: ${{ github.sha }}

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: dev
          cluster-name: echo-dev-cluster

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.9.4"

      - name: Deploy in development environment
        run: >-
          helm upgrade echo ./k8s
          --namespace echo --create-namespace
          --install -f k8s/.ignore/values.yaml --wait
